No   Name   Ratings   Yes/no
1    AK        3        ~
2    BK        4        Y
3    CK        4        Y
4    DK        3        Y
5    EK        2        N
6    FK        3        ~
7    GK        1        N
8    HK        5        Y
9    IK        4        Y
10   JK        4        Y  
